version: 2
references:
  defaults: &defaults
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/package

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: /root/package
          paths:
            - ./*

  build-and-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/package
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Release to npm
          command: npm run semantic-release || true

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/package
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run eslint
          command: npm run lint-eslint

  check-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/package
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run eslint
          command: npm run lint-ts

  lint-commits:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/package
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run eslint
          command: npm run lint-commit

workflows:
  version: 2

  build-and-publish:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - check-types:
          requires:
            - install-dependencies
      - build-and-publish:
          requires:
            - lint
            - check-types
          filters:
            branches:
              only:
                - master
